"""Auto-generated by learn.py: Figure src with leading slash — broken on GH Pages."""
import re
from pathlib import Path

CONTENT = Path("content")
PATTERN = re.compile(r'\{\{<\s*figure\s+src="/[^"]*"', re.MULTILINE)

def run():
    files = [f for f in CONTENT.rglob("*.md") if f.name != "_index.md"]
    issues = []
    for fp in sorted(files):
        text = fp.read_text("utf-8")
        for m in PATTERN.finditer(text):
            line_no = text[:m.start()].count("\n") + 1
            rel = fp.relative_to(CONTENT)
            issues.append(f"  {rel}:{line_no}  figure src uses leading slash")
    return issues
